### ISSUE TITLE
About many to many relationship.

### ISSUE THREAD

**Issue by YedilSerzhan** [EdilSerjan/EntityFramework#2]
The entity "course" and the entity "member" is many to many relationship, that's why I created the 3rd entity "schedule" to support it.
@nightBaker

**Comment by nightBaker** [comment]
I see, however it confuses readers of your code. Could you **rename** schedule to **CourseMember** ?

**Comment by YedilSerzhan** [comment]
Okay, just renamed the class **Schedule** to **CourseMember** and also changed the** id fields** in views to **name fields** as you requested in the dl comment, please have a look and grade it please. @nightBaker

**Comment by nightBaker** [comment]
Mr. Kairat will grade your changes. Close issue please.
