### ISSUE TITLE
About Milestone 3

### ISSUE THREAD

**Issue by YedilSerzhan** [EdilSerjan/EntityFramework#3]
Dear sir @nightBaker
I'm wondering if you could provide us an example project of unit testing , so that we can have a direct reference to look at.

**Comment by nightBaker** [comment]
https://github.com/nightBaker/iitu/tree/master/week%209/iitu.web.example

**Comment by YedilSerzhan** [comment]
Thank you sincerely!

**Comment by nightBaker** [comment]
Let me know if you have any problems with example
